[package]
name = "ethercat-plc"
description = "Tools to build a PLC like program using the ethercat crate"
keywords = ["ethercat", "plc", "automation"]
version = "0.2.0"
authors = ["Georg Brandl <g.brandl@fz-juelich.de>"]
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
log = "0.4.6"
libc = "0.2.49"
time = "0.1.42"
mlzlog = "0.5.1"
byteorder = "1.3.1"
crossbeam-channel = "0.3.8"
ethercat = "0.1.3"
ethercat-derive = { path = "../ethercat-derive", version = "0.1.3" }
